plugins:
  - jekyll-sitemap
theme: jekyll-theme-cayman
title: Dale Wright
description: <p>Experienced strategist, consultant and leads. Enjoys thinking about our future.</p>Helps lead projects at the intersection of health and technology.
