theme: jekyll-theme-cayman
title: Dale Wright
description: Experienced strategist and consultant. Works at the exciting intersection of health and technology. Partners with mission-driven teams to create value.
