theme: jekyll-theme-cayman
title: Dale Wright
description: Experienced strategist, analyst and consultant. Working at the intersection of health and technology. Committed to partnering with mission-driven teams to create value.</
