theme: jekyll-theme-cayman
title: Dale Wright
description:
[Email](mailto:resume@dalewright.com) | [Twitter](https://www.twitter.com/dalecraigwright) | [LinkedIn](https://www.linkedin.com/in/dalecraigwright)
