theme: jekyll-theme-cayman
title: Dale Wright
description: <p>Experienced Strategist, Analyst and Consultant. Working at the intersection of Health and Technology.<p>Committed to partnering with mission-driven teams to create value.</p>

