theme: jekyll-theme-cayman
title: Dale Wright
description: <a href="mailto:dale@dalewright.com">Email</a> | <a href="https://www.twitter.com/dalecraigwright">Twitter</a> | <a href="https://www.linkedin.com/in/dalecraigwright">LinkedIn</a>
