plugins:
  - jekyll-sitemap
theme: jekyll-theme-cayman
title: Dale Wright
description: <p><strong>Experienced strategist, consultant and leader.</strong></p>Enjoys thinking about our future. Leads projects at the intersection of health and technology.
