plugins:
  - jekyll-sitemap
theme: jekyll-theme-cayman
title: Dale Wright
description: <p>Experienced strategist, consultant and leader.</p>Enjoys thinking about our future. Helps lead projects at the intersection of health and technology.
