theme: jekyll-theme-cayman
title: Dale Wright
description: Experienced strategist and consultant. Working at the intersection of health and technology. Partners with mission-driven teams to create value.
