plugins:
  - jekyll-sitemap
theme: jekyll-theme-cayman
title: Dale Wright
description: I am endlessly curious and committed to making a difference. Working at the intersection of healthcare and information technology is a great privilege. I am seeking new opportunities to leverage established and emerging technologies to help improve the health and happiness of every Australian. 
