plugins:
  - jekyll-sitemap
theme: jekyll-theme-cayman
title: Dale Wright
description: Experienced strategist, consultant and leader. Enjoys thinking about our future. Helpa leads projects at the intersection of health and technology.
