theme: jekyll-theme-cayman
title: Dale Wright
description: <p>Experienced strategist, consultant and analyst.</p> <p>Working at the intersection of health and technology.<br> Committed to partnering with mission-driven teams to create value.</p>

